spring:
    config:
        activate:
            on-profile: dev

logging:
    level:
        root: INFO
        com.nextspringkart: DEBUG
        org.springframework: INFO
        org.springframework.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
    expiration: 3600000 # 1 hour

